### PR TITLE
Making the config file more user friendly for whitelist/nevertransfer…

### PR DESCRIPTION
**Pull request by XCrimsyX**
…/ignorecatching by changing it from number to the ENUM name

### CODE REVIEW

**Comment by SippieCup** [comment]
Looks great, thanks for doing this. I'll probably merge it in after the API issues are resolved so that it is an easier transition.

**Comment by XCrimsyX** [comment]
Cool thanks! :)

**Comment by SippieCup** [comment]
Hey Crimsy, if you can please resolve the conflicts with the newest build and I'll commit it.

**Comment by XCrimsyX** [comment]
Hey I resolved the conflicts :)

**Pull request merged**
