### PR TITLE
Fix e in toasts

### PR DESCRIPTION
**Pull request by kyleshrader**
I'm pretty sure this is how you do it... **but can someone make sure this works**? i can't right now.

shows Poke00E9mon evolved/caught/Stop in toasts...

### CODE REVIEW

**Comment by RobertMcCoy** [comment]
This has already been fixed in the most recent version, you might want to sync or rebase with the master repo to see the change.

**Comment by kyleshrader** [comment]
Can you link me to the fix?

**Comment by kyleshrader** [comment]
923403756e707f45ebf9e6cdb5e3d51256fb65e0 is not the same

**Comment by kyleshrader** [comment]
Oh gotcha... bot was probably running on old version, but code was updated... this PR will break it again! :( sorry

**Comment by BurakDev** [comment]
@kyleshrader I think depends of platform, what is your platform ? My previous fix work on Windows 10 x64 and Ubuntu 14.04..

**Comment by kyleshrader** [comment]
Nope, works after i restarted bot... My bad :/

**Comment by BurakDev** [comment]
Oh okay ! :+1:

**Pull request closed without merging**
