### PR TITLE
Fix issue with no family id

### PR DESCRIPTION
**Pull request by kyleshrader**
I am seeing a NPE on the family for Hypno/Drowzee

### CODE REVIEW

**Comment by SwipeX** [comment]
Why would this not trigger for Pinser?

**Comment by kyleshrader** [comment]
Pinser works fine for me. And even the drowzee. But for some reason, HYPNO isn't working.

**Comment by kyleshrader** [comment]
So I know before, Hypno was missing and was commented out. But he was added "speculatively" here: https://github.com/AeonLucid/POGOProtos/pull/21

**Comment by SwipeX** [comment]
So most likely the value for Hypno is incorrect in the API?

**Comment by SwipeX** [comment]
@kyleshrader Hypno evolves from drowsee???

**Comment by kyleshrader** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/adab2ab8b19665b801fda188e0548ef7b74cbc8d/src/main/java/com/pokegoapi/api/pokemon/PokemonMetaRegistry.java

This is where it was commented out.

Yes.

**Comment by kyleshrader** [comment]
So yeah, API needs to fix it on their end.

**Pull request merged**
