### PR TITLE
Add item and Pokemon management UI

### PR DESCRIPTION
**Pull request by Hawkey3s**
User can now delete item and transfer monster using UI.

Will be adding evolving Pokemon UI later

Screenshots:
items

pokemon

### CODE REVIEW

**Comment by SwipeX** [comment]
In my opinion, this would work MUCH better with a right click option.

**Comment by SwipeX** [comment]
But I really like the idea.

**Comment by Hawkey3s** [comment]
Can you review it, it's ok feature to have i.e user may want to keep some items and only remove a specific item. currently drop list is hard coded in DropItems, there's no config for this so this UI will come in handy :)

**Comment by Hawkey3s** [comment]
Until we finish the electron ui

**Comment by SwipeX** [comment]
Right click menu should be quite easy to implement in JQuery, and you can still use the same code essentially. These are not visually appealing.

**Comment by Hawkey3s** [comment]
Right click menu on a template that reloads every 5 seconds is not a good implementation I think.
As for appealing, we'll be moving away from Javavfx anyway. Most of the UI code will need to be rewritten. Forget about visual appearance for now and go with functionality XD

**Comment by SwipeX** [comment]
You may have a point there about right clicking, however the new front end will use the same html, and most of the javafx features will be re-written in node.js

so something like a button/link to transfer would work well and be preserved.

**Comment by Hawkey3s** [comment]
Most of the front end code will need to be rewritten if we move away from javafx.
Currently our front end does not have communicate with the back end directly, but have the backend look up changes on the UI.
The only feature that should be kept is the google map because there's no communication from the front end to back end in this case. Unless we'll support a feature that allow user to play pokemon go manually using our bot -_-

**Comment by pisuth** [comment]
So what's the thought on this pr? Please let me know so I can keep continue working on something else from the same or new branch.

**Comment by SwipeX** [comment]
I think a very small remove button would suit nicely for this feature set.

**Comment by SwipeX** [comment]
with the current layout keeping the same.

**Comment by pisuth** [comment]
The current layout refresh itself every few seconds. I make it so that those 2 new layouts do not keep refreshing themselves so they're more suitable for waiting for user input.

**Comment by pisuth** [comment]
I can add a popup modal for item recycling, but pokemon management is ok as it is I believe.

**Comment by SwipeX** [comment]
@pisuth Not inclined to push it how it is. Maybe have it look more visually appealling

**Pull request closed without merging**
