### PR TITLE
Save Strong Pokemon

### PR DESCRIPTION
**Pull request by MrMonotone**
Release the weak pokemon only if there is another one of them.

### CODE REVIEW

**Comment by kylestev** [comment]
Looks like you or your editor converted spaces into tabs. Might want to fix that.

**Comment by SwipeX** [comment]
^true
and I dont actually see any differences, `list.indexOf(p) < list.size() - 1` is just moved down to its own if statement.  Or can you explain to me what the code change is here?

**Comment by MrMonotone** [comment]
If you filter everything first, you will not save all the high IV Pokemon if they are duplicated. Moving that line down allows you to save multiple high IV Pokemon of the same type.

**Comment by MrMonotone** [comment]
for example if I see two perfect eevees they will be filtered out since the bot only saves one now. If I move the if statement down like I did it will see that that other eevee is good and keep it. I though people would want multiple perfect Pokemon so it makes sense to me. There is another change that can be made to move the cp min down as well. But that is unrelated.

**Comment by kyleshrader** [comment]
I don't think that is true. It currently keeps 1. The highest CP pokemon; 2. All pokemon above the IV threshhold; 3. All pokemon above the CP threshold; 4. All pokemon which are favorited... Any which do not fall in one of those 4 is then disgarded. So unless your iv-ratio is > 100, you will always keep all perfects

**Comment by MrMonotone** [comment]
Maybe I misunderstood then.

**Pull request closed without merging**
