### PR TITLE
New feature&bug fix

### PR DESCRIPTION
**Pull request by mxc1868**
New feature:
1. When not setting the preferred ball, it will follow the priority that
POKEBALL>GREATBALL>ULTRABALL>MASTERBALL
2. Showing remaining balls info when catching pokemons
3. Users can set the searching range in config file

Bug fix:
CP filter bug

### CODE REVIEW

**Comment by MrMonotone** [comment]
:+1:

**Comment by null-dev** [comment]
Why not, have the users set a comma delimited list of pokeball types in the config like this:
`pokeball_order=POKEBALL,GREATBALL,ULTRABALL,MASTERBALL`

This list will specify the order to use pokeballs in.

So, when using pokeballs, we follow the list trying each pokeball type from the first entry to last until we find one that works.

**Comment by SwipeX** [comment]
Ill try to use some of your Ideas.
- You were not on the latest revision, so that will cause some merge errors
- Giant if statements are not your friend :) Think of a better way to do it with maybe a loop?

**Comment by MrMonotone** [comment]
@SwipeX there are a couple of different variance variables around the code. Don't they all serve the same purpose? Look at this commit the walking still goes outside of the search area. It might be a good idea to merge them all.

**Comment by SwipeX** [comment]
@MrMonotone the walking can slightly go out due to directions API, but not by much. Ive added new configurations in the latest b7c664ff42aab4285dfe03afb5cddceb92230d3d

**Comment by SwipeX** [comment]
This is essentially merged by me,

**Comment by mxc1868** [comment]
Sorry for my UGLY code. I just begin to learn how to use Github :D

**Pull request closed without merging**
