### PR TITLE
Add %IV to gui

### PR DESCRIPTION
**Pull request by agusmba**
Added `%IV` to pokemons on the GUI.

Also log info on removed items.

### CODE REVIEW

**Comment by jeffsnow88** [comment]
Nice! So how we users keep the code updated? Do we need to download and import the project every time there is a change, or there is easier way? Thanks.

**Comment by agusmba** [comment]
@jeffsnow88 I guess the project is moving rapidly. Check SwipeX's commits, he's working on it non-stop!
He released a new tagged version today,  but if you want to have the bleeding edge, you'll have to clone the repo and build it yourself. No need to download manually, just git fetch, git pull...

**Comment by jeffsnow88** [comment]
Sounds good man. Excellent work here. Let's see if get some time to understand the code and collaborate. Or even if I can bring some new ideas. Thank you.

**Comment by kylestev** [comment]
@jeffsnow88 you can follow the releases at https://github.com/SwipeX/PokeMate/releases. Those releases will typically have fewer bugs than just running the code from the master branch of this repo.

**Comment by SwipeX** [comment]
Hopefully this looks fine. Ill check tomorrow.

**Pull request merged**
