### PR TITLE
Adding log4j2 support / example in PokeMate class

### PR DESCRIPTION
**Pull request by gffde3**
Just adding better support for console messaging / debugging by:
- adding log4j2 in gradle
- log4j2.xml in resources
- adding a few example replacement logger messages in PokeMate class

This will setup easier debugging / messaging / logging for the application.

### CODE REVIEW

**Comment by gffde3** [comment]
In lieu of being on slack (welp!), this was one of the things I was going to be putting in was a bit more transparency in logging.

Not sure why the travis build failed given I hadn't changed the DropItems class. vOv

**Comment by SippieCup** [comment]
Hey gffde3, I'll get you a slack invite shortly. Thanks for the PR!

**Comment by gffde3** [comment]
Cheers, just saw that you were sticking in print statements for debugging and figured it'd be cleaner to use a logger where you could put in debug / info / trace messages and just change the log level ;) (plus allow more detailed dump messages to go to a file for feedback in issues).

**Comment by SippieCup** [comment]
@gffde3 can you fix the compile errors with merging to newest build? thanks!

**Comment by gffde3** [comment]
No problem. I'll merge back and see.

**Comment by gffde3** [comment]
Donesky

**Comment by SippieCup** [comment]
By the way, you can join slack again!

**Pull request merged**
