### PR TITLE
Accept Level-Up rewards

### PR DESCRIPTION
**Pull request by Messna**
Bot should now receive the Level-Up rewards.

### CODE REVIEW

**Comment by kylestev** [comment]
Please use 4 spaces for indentation instead of tabs.

In addition, please take note of the code quality checks mentioned by [codacy](https://www.codacy.com/app/timdeka/PokeMate/pullRequest?prid=297790) for this PR.

👎 for now @SwipeX don't merge just yet.

**Comment by kylestev** [comment]
Thank you for the contribution, though! If you make those changes I'll merge this PR 😄

**Comment by kylestev** [comment]
I've added an `.editorconfig` dot file to assist editors in knowing what style we use for line feeds and indentation.

**Comment by SwipeX** [comment]
Looks good, just please use the spaces! :)

**Pull request closed without merging**
